"""add_note_enrichment_fields

Revision ID: 2b5ab692457d
Revises: 0a358a078485
Create Date: 2026-01-19 14:02:40.550764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5ab692457d'
down_revision: Union[str, None] = '0a358a078485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('external_display_url', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'enriched_at')
    op.drop_column('notes', 'followers_count')
    op.drop_column('notes', 'external_display_url')
    # ### end Alembic commands ###
