"""add_company_pb_id_to_notes

Revision ID: 6312eb89fded
Revises: 2b5ab692457d
Create Date: 2026-01-19 14:08:50.327999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6312eb89fded'
down_revision: Union[str, None] = '2b5ab692457d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('company_pb_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_notes_company_pb_id'), 'notes', ['company_pb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_company_pb_id'), table_name='notes')
    op.drop_column('notes', 'company_pb_id')
    # ### end Alembic commands ###
